# Site settings
title: bostonou
email: hey@bostonou.com
description: > # this means to ignore newlines until "baseurl:"
  My site.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://bostonou.com" # the base hostname & protocol for your site
twitter_username: bostonou

# Build settings
markdown: kramdown

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

collections:

permalink: /blog/:title.html

